### ISSUE TITLE
想请教几个实现的问题

### ISSUE THREAD

**Issue by BEWINDOWEB** [Cicizz/jmqtt#17]
1、如何持久化的消息呢？
一般的MQTT Broker，像EMQ、Mosquitto，都会使用基于内存的消息队列，我之前就一直想把EMQ的分布式内存消息队列Mnesia替换为kafka，但是不知道该如何操作。在EMQ的收费版白皮书里面，有一个双向箭头，不知道是不是替换了：
![image](https://user-images.githubusercontent.com/6178098/50943576-ff8d2b80-14c7-11e9-9971-1a9211fe7606.png)
所以这个是用RabbitMQ来做的消息队列吗，怎么去实现的呢？
2、多消费者消费同一个主题
一般Message Broker只是用来转发给后面的业务，后面的业务必然是集群，必然有多个worker。如何保证多个消费者消费同一个主题的时候，只有一个消费者得到呢？就是一条消息只消费一次。EMQ3.0的集群共享订阅就支持这个负载均衡。
3、安全验证
这里是如何进行安全验证的呢，应该在哪一步来操作呢。我开始的想法是在Message Broker前面有一个安全校验层，但是这样做的话，Websocket就过不来Message Broker了，该怎么办呢。

希望大佬能给点建议，谢谢。

**Comment by Cicizz** [comment]
@BEWINDOWEB 你好。
我自己没有使用过EMQ，就说下Jmqtt这几块的处理以及想法吧:.
1.关于消息存储：
  首先基于内存的方案基本是不可行的，主要是内存容量很有限，对于mqtt的消息主要有两类：
  第一类是过程消息（qos1,qos2），这类消息临时保存，可以基于内存，并定时刷新到磁盘即可（未确认的离线消息）
   第二类是离线消息，这类消息目前jmqtt的存储考虑主要用rocksdb自己进行封装，不过用rocketmq也是可以的，根据rocketmq的key来查询获取消息。后续jmqtt会考虑数据与kafka的交互
2.关于集群消息：
  MQTT协议里只提供的Topic与订阅方式主要是广播消费的，并且MQTT的topic与Kafka,RocketMQ也不一样，支持很多Topic，所以如果需要集群消费，可以从业务上改造，因为mqtt是有cleansession这个属性的，支持kafka或rocketmq那种集群不太合适，所以mqtt的支持点对点消息更合适，jmqtt支持点对点消息是发送端必须制定接收端的clientId，并按照一定规则（即时通讯的效果）
3.安全验证：
  安全验证主要有三块可以着手去做：
  1.协议层的安全：SSL/TLS/WSS等，这块其实通过负载均衡来做更好，不过Jmqtt后序会在netty上实现一个版本，不过不提倡直接使用，亲测SSL比较耗性能，哈哈
   2.访问安全，mqtt协议里有账号密码，可以每个client对应的账号或密码进行验证
   3.连接，发布，订阅：针对每个client,topic做权限控制，甚至clientId可以制定规则（groupId@clientId）这样子，限制每个groupId的连接数。
以上三种是Jmqtt后续会做的安全方面的工作，对于你说的限制websocket啥的，其实通过这三个方案已经可以做了。个人建议在应用层做处理扩展性较好。
 谢谢

**Comment by BEWINDOWEB** [comment]
@Cicizz 嗯嗯~
还有就是，为什么不能直接使用Kafka这类MQ来做Message Broker呢？Message Broker核心就是：连接、订阅树、消息队列。直接连接之后放入消息队列就好了，为什么还要做订阅树、节点路由之类的东西呢，客户端自己订阅分布式消息队列Topic就行了呀；除了这些，Jmqtt做了哪些其他的处理吗？

**Comment by Cicizz** [comment]
@BEWINDOWEB 
1.Kafka以及rocketmq的topic都只支持1个topic，mqtt的topic有很多级
2.kafka主要是系统级的消息中间件，是高并发请求的，mqtt有百万级设备连接，消息较小，但也属于高并发连接和高并发请求的，如果都订阅很多Topic，kafka是支持不了这么多topic和订阅关系的
3.kafka的集群有zk这些东西，jmqtt后续所有核心组件都会自己实现，比较轻量级，kafka,rocketmq这些会以一种插件队列的方式在Jmqtt使用，只是提供一种可选型的方案，并且kafka这种只适合存储消息，例如mqtt的订阅关系，client会话信息等还是需要自己处理的。

jmqtt的目标是自己可以独立自己部署，并实现横向集群扩展，数据可靠性存储以及可运维接口，包括设备管理，broker管理，订阅管理等。
并提供kafka，rocketmq等消息队列进行消息上行采集接口

**Comment by BEWINDOWEB** [comment]
@Cicizz 
所以一般消息较小，放在内存不会有问题的是吗？kafka只是用来单向流出数据供后端服务使用，不用来持久化内存里面的消息的是吗？
那这样扩容不就得增加内存而不是增加磁盘了……
Issue快变成聊天室了，可否加QQ 875302177 交流一下，因为有些细节很困惑，我也是在考虑是否自己重新做一个简单的broker版本。
多谢

**Comment by Cicizz** [comment]
@BEWINDOWEB 
你可以去研究下mqtt协议，
Kafka是要做消息持久的哈。
你可以加我微信Callmez2013
