### ISSUE TITLE
Why not to abort the connection that failed to authenticate

### ISSUE THREAD

**Issue by zhenyue541** [Cicizz/jmqtt#32]
I mean why the broker does not call the method "channel.close()" after replying to the ack message that the authentication failed.
https://github.com/Cicizz/jmqtt/blob/7e6a46152adfbb4febe3267360adc0ec15716030/jmqtt-broker/src/main/java/org/jmqtt/broker/processor/ConnectProcessor.java#L63-L71
https://github.com/Cicizz/jmqtt/blob/7e6a46152adfbb4febe3267360adc0ec15716030/jmqtt-broker/src/main/java/org/jmqtt/broker/processor/ConnectProcessor.java#L111-L114

**Comment by Cicizz** [comment]
@zhenyue541   Thanks ,this is a bug ,i have fixed it

**Comment by BEWINDOWEB** [comment]
This bug has fixed at https://github.com/Cicizz/jmqtt/commit/136a60b5fd8843c6c52cad0c046fe47086cb6362, so we will close it.
