### ISSUE TITLE
the method containSendMsg in DefaultFlowMessageStore has bug

### ISSUE THREAD

**Issue by pptttiger** [Cicizz/jmqtt#55]
return this.sendCache.get(clientId).contains(msgId);
should be
return this.sendCache.get(clientId).containsKey(msgId);

**Comment by Cicizz** [comment]
Thanks，I'll see it later

**Comment by BEWINDOWEB** [comment]
It has been fixed at https://github.com/Cicizz/jmqtt/commit/197a9c37f446d94d68fe17a1d03630a24ecf126d, thanks for your issue.
