### ISSUE TITLE
3.0的内容没有开发吗？代码里好像没有。

### ISSUE THREAD

**Issue by jiangxingang** [Cicizz/jmqtt#57]
支持简单运维功能
支持RocketMQ Bridge
支持Kafka Bridge
支持$SYS Topic监控

这些好像都没有。拉了MASTER

**Comment by Cicizz** [comment]
你好，正在开发3.0的功能，3.0会重构集群，重构集群后会再看法上述功能的，谢谢关注，3.0版本预计10.7号后会发一个版本
